name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Print environment info
        run: |
          echo "Node version: $(node -v)"
          echo "pnpm version: $(pnpm -v)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "apps/hub directory contents:"
          ls -la apps/hub/

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check apps/hub package.json
        run: |
          echo "apps/hub package.json:"
          cat apps/hub/package.json
          echo "apps/hub next.config.js:"
          head -20 apps/hub/next.config.js

      - name: Build apps/hub with verbose output
        run: |
          cd apps/hub
          echo "Building from directory: $(pwd)"
          pnpm build 2>&1 | tee build.log
          echo "Build log:"
          cat build.log

      - name: Verify build
        run: |
          echo "Checking build output:"
          ls -la apps/hub/.next/ || echo "No .next directory found"
          test -f apps/hub/.next/BUILD_ID && echo "BUILD_ID found" || echo "BUILD_ID not found"